#!/bin/bash
echo -e -n "Adding \e[4;93m"$1"\e[00m to ignore list: "
git update-index --assume-unchanged $1 1>~/tmp/gitignoreadd 2>~/tmp/gitignoreadd
if [[ $? -ne 0 ]]; then
	echo -e "\e[37;41mError!\e[00m";
	cat ~/tmp/gitignoreadd
else
	echo -e "\e[00;32mDone.\e[00m";
fi;